# SPDX-FileCopyrightText: 2023 Carl Zeiss Microscopy GmbH
#
# SPDX-License-Identifier: MIT

# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes
  - C
  - JSON
  - EDITORCONFIG
  - YAML
  - MARKDOWN
  - REPOSITORY
DISABLE_LINTERS: 
  - REPOSITORY_GITLEAKS
  - CSHARP_DOTNET_FORMAT
  - CSHARP_CSHARPIER
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - REPOSITORY_CHECKOV
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_SECRETLINT
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - REPOSITORY_TRIVY
  - XML_XMLLINT
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK # Make non-blocking due to network timeouts etc.
CPP_CPPLINT_ARGUMENTS: --verbose=2 --linelength=300 --filter=-whitespace/braces,-whitespace/indent,-whitespace/comments,-whitespace/newline,-build/c++11,-build/include_subdir,-build/namespaces,-build/include_order,-whitespace/end_of_line,-runtime/indentation_namespace,-runtime/references,-readability/namespace,-readability/nolint
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
UPDATED_SOURCES_REPORTER: false
TEXT_REPORTER: true
EMAIL_REPORTER: false
VALIDATE_ALL_CODEBASE: true